### ISSUE TITLE
Changes the predicate or _isNotPrivate condition

### ISSUE THREAD

**Issue by juliomatcom** [alvaropinot/omitprivatekeys#1]
Would be nice if a can pass directly and optionaly another predicate or change the _isNotPrivate condition to another pattern or regex (without touch in the module), i have seen some codes where devs use another conventions to define "private" functions like '$$' or :bomb:  . 

Esta genial, gracias Alvaro :fire:

**Comment by alvaropinot** [comment]
Yep, really nice idea, thought about that earlier this morning. I would love to see a PR from you :)

Indeed the private bombs are awesome!!
